"""Secure Assembler service.

Composes certified components and constrained glue code into
complete, working programs. Glue code is generated by Claude
with strict constraints: no direct I/O, no crypto, no auth —
only data transformation and control flow.
"""

import json
import structlog

from aijailer.schemas.intent import CodeIntent
from aijailer.services.constraint_engine import ConstraintResult

logger = structlog.get_logger(__name__)

# Strict prompt for glue code generation
ASSEMBLER_SYSTEM_PROMPT = """You are a secure code assembler. You generate ONLY glue code that
wires together pre-certified security components. You MUST follow these rules:

ABSOLUTE RULES (violation = immediate rejection):
1. NO direct I/O operations (no open(), no requests.get(), no socket)
2. NO cryptographic operations (no hashlib, no hmac, no secrets directly)
3. NO authentication logic (no password checking, no token creation)
4. NO raw SQL or database queries (no cursor.execute, no raw SQL strings)
5. NO string concatenation with user inputs for any sensitive operation
6. NO eval(), exec(), or dynamic code execution
7. NO subprocess or os.system calls

YOU MAY ONLY:
- Import and call functions from the certified_components modules provided
- Perform data transformation (mapping, filtering, formatting)
- Implement control flow (if/else, loops, error handling)
- Define function signatures and type hints
- Use Pydantic models for validation
- Add docstrings and comments

OUTPUT FORMAT:
- Complete, runnable Python module
- All imports at the top
- Full type hints on all functions
- Docstrings on all public functions
- Error handling with try/except
"""


class SecureAssembler:
    """Assembles secure code from certified components + constrained glue code."""

    def __init__(self, api_key: str | None = None):
        self._api_key = api_key
        self._client = None

    def _get_client(self):
        """Lazy-initialize the Anthropic client."""
        if self._client is None:
            try:
                import anthropic
                self._client = anthropic.Anthropic(api_key=self._api_key)
            except ImportError:
                raise RuntimeError(
                    "anthropic package is required for secure assembly. "
                    "Install with: pip install anthropic"
                )
        return self._client

    async def assemble(
        self,
        intent: CodeIntent,
        constraint_result: ConstraintResult,
        selected_components: list[str],
        language: str = "python",
        framework: str | None = None,
    ) -> str:
        """Assemble secure code from intent + constraints + components.

        Steps:
        1. Build a component API reference from selected components
        2. Create a strict prompt with the ASSEMBLER_SYSTEM_PROMPT
        3. Generate constrained glue code via Claude
        4. Return the complete module
        """
        component_api = self._build_component_api(selected_components)
        requirements = self._build_requirements(intent, constraint_result)

        prompt = f"""Generate secure {language} code for the following intent:

INTENT: {intent.description or intent.action.value}
FRAMEWORK: {framework or 'none specified'}
LANGUAGE: {language}

SECURITY REQUIREMENTS (from constraint engine):
{requirements}

AVAILABLE CERTIFIED COMPONENTS (use ONLY these for security operations):
{component_api}

Generate a complete, working module that fulfills the intent using ONLY
the certified components listed above for all security-sensitive operations.
Include proper error handling and type hints."""

        try:
            client = self._get_client()

            message = client.messages.create(
                model="claude-sonnet-4-20250514",
                max_tokens=4096,
                system=ASSEMBLER_SYSTEM_PROMPT,
                messages=[{"role": "user", "content": prompt}],
            )

            code = message.content[0].text.strip()

            # Extract code from markdown code blocks if present
            if "```python" in code:
                code = code.split("```python")[1].split("```")[0].strip()
            elif "```" in code:
                code = code.split("```")[1].split("```")[0].strip()

            logger.info(
                "assembler.code_generated",
                intent_action=intent.action.value,
                components_used=selected_components,
                code_length=len(code),
            )
            return code

        except Exception as e:
            logger.error("assembler.generation_failed", error=str(e))
            raise RuntimeError(f"Secure assembly failed: {e}")

    def _build_component_api(self, components: list[str]) -> str:
        """Build an API reference string for the selected components."""
        # Component API summaries
        component_apis = {
            "safe_query_builder": (
                "from certified_components.data_access import safe_query_builder\n"
                "  safe_query_builder.insert(table, data) -> id\n"
                "  safe_query_builder.select(table, conditions) -> list[dict]\n"
                "  safe_query_builder.update(table, conditions, data) -> int\n"
                "  safe_query_builder.delete(table, conditions) -> int"
            ),
            "input_validator": (
                "from certified_components.data_access import input_validator\n"
                "  input_validator.validate(data, schema) -> ValidatedData"
            ),
            "output_encoder": (
                "from certified_components.data_access import output_encoder\n"
                "  output_encoder.encode(data, context='html'|'url'|'js') -> str"
            ),
            "session_manager": (
                "from certified_components.auth import session_manager\n"
                "  session_manager.create(user_id) -> Session\n"
                "  session_manager.validate(token) -> Session\n"
                "  session_manager.revoke(session_id) -> None"
            ),
            "jwt_handler": (
                "from certified_components.auth import jwt_handler\n"
                "  jwt_handler.create_token(payload) -> str\n"
                "  jwt_handler.verify_token(token) -> dict"
            ),
            "hashing": (
                "from certified_components.crypto import hashing\n"
                "  hashing.hash_password(password) -> str\n"
                "  hashing.verify_password(password, hash) -> bool"
            ),
            "encryption": (
                "from certified_components.crypto import encryption\n"
                "  encryption.encrypt(plaintext, key_ref) -> bytes\n"
                "  encryption.decrypt(ciphertext, key_ref) -> bytes"
            ),
            "http_client": (
                "from certified_components.network import http_client\n"
                "  http_client.get(url, headers) -> Response\n"
                "  http_client.post(url, data, headers) -> Response"
            ),
            "safe_file_io": (
                "from certified_components.primitives import safe_file_io\n"
                "  safe_file_io.read(path, allowed_dirs) -> bytes\n"
                "  safe_file_io.write(path, data, allowed_dirs) -> None"
            ),
            "safe_subprocess": (
                "from certified_components.primitives import safe_subprocess\n"
                "  safe_subprocess.run(command, allowed_commands) -> Result"
            ),
            "hipaa_audit_logger": (
                "from certified_components.compliance import hipaa_audit_logger\n"
                "  hipaa_audit_logger.log_event(action, entity_id, actor) -> None"
            ),
            "pci_data_handler": (
                "from certified_components.compliance import pci_data_handler\n"
                "  pci_data_handler.mask_card_number(number) -> str\n"
                "  pci_data_handler.tokenize(card_data) -> str"
            ),
        }

        apis = []
        for comp in components:
            if comp in component_apis:
                apis.append(component_apis[comp])
            else:
                apis.append(f"# {comp}: API reference not available")

        return "\n\n".join(apis)

    def _build_requirements(
        self, intent: CodeIntent, constraint_result: ConstraintResult
    ) -> str:
        """Build a requirements string from constraint violations."""
        reqs = []
        for v in constraint_result.violated_constraints:
            if isinstance(v, dict):
                reqs.append(f"- [{v.get('severity', 'HIGH')}] {v.get('requirement', '')}")
                reqs.append(f"  Use component: {v.get('enforced_component', 'N/A')}")
        if intent.compliance_domains:
            reqs.append(f"- Compliance: {', '.join(intent.compliance_domains)}")
        if intent.error_sensitivity:
            reqs.append(f"- Error handling: {intent.error_sensitivity.value}")
        return "\n".join(reqs) if reqs else "No special security requirements."

    def select_components(
        self, intent: CodeIntent, constraint_result: ConstraintResult
    ) -> list[str]:
        """Select certified components needed for this intent."""
        components = set()

        # Always include input validation for user input
        if any("user_input" in str(s) for s in intent.input_sources):
            components.add("input_validator")

        # Database operations
        if intent.action in ("create", "read", "update", "delete"):
            components.add("safe_query_builder")

        # Auth requirements
        if intent.auth_context.value != "none":
            components.add("session_manager")
            if intent.auth_context.value == "token":
                components.add("jwt_handler")

        # Crypto
        if intent.action == "crypto" or intent.action == "auth":
            components.add("hashing")

        # Compliance
        for domain in intent.compliance_domains:
            if domain == "HIPAA":
                components.add("hipaa_audit_logger")
            elif domain == "PCI-DSS":
                components.add("pci_data_handler")

        # Browser output
        if any("browser" in str(t) for t in intent.output_targets):
            components.add("output_encoder")

        # File I/O
        if intent.action == "file_io":
            components.add("safe_file_io")

        # Add components from constraint violations
        for v in constraint_result.violated_constraints:
            if isinstance(v, dict) and "enforced_component" in v:
                components.add(v["enforced_component"])

        return list(components)


# Singleton
_assembler: SecureAssembler | None = None


def get_secure_assembler(api_key: str | None = None) -> SecureAssembler:
    global _assembler
    if _assembler is None:
        _assembler = SecureAssembler(api_key=api_key)
    return _assembler
