"""Security Constraint database model.

Stores constraint rules that enforce secure code generation patterns.
Constraints are loaded from YAML definitions or auto-generated by
the immune memory system in response to attack patterns.
"""

import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, String, func
from sqlalchemy.dialects.postgresql import UUID
from aijailer.db.types import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from aijailer.db.base import Base


class Constraint(Base):
    __tablename__ = "constraints"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    category: Mapped[str] = mapped_column(String(100), nullable=False)
    severity: Mapped[str] = mapped_column(
        String(20), nullable=False
    )  # CRITICAL, HIGH, MEDIUM, LOW

    # Constraint logic
    applies_when: Mapped[dict] = mapped_column(JSONB, nullable=False)  # Condition predicates
    rules: Mapped[dict] = mapped_column(JSONB, nullable=False)  # Constraint rules

    # Origin tracking
    source: Mapped[str] = mapped_column(
        String(50), nullable=False
    )  # manual, immune_response, cve_feed

    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
